# Generated by Django 3.2.6 on 2021-08-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_imgs'),
        ),
    ]
